export const projects = [
    {
    id: 1,
    project_title: "E-commerce Website",
    project_description: "A fully-featured e-commerce website with user authentication, product catalog, and payment gateway integration.",
    tech_stack: ["HTML/CSS", "JavaScript", "React", "Node.js", "Express", "MongoDB"],
  },
  {
    id: 2,
    project_title: "Mobile Expense Tracker App",
    project_description: "A mobile app that helps users track their expenses and manage their budget.",
    tech_stack: ["React Native", "Firebase"],
  },
  {
    id: 3,
    project_title: "Social Media Dashboard",
    project_description: "A dashboard for monitoring social media engagement and analytics.",
    tech_stack: ["Vue.js", "Python", "Django", "PostgreSQL"],
  },
  {
    id: 4,
    project_title: "Inventory Management System",
    project_description: "An inventory management system for tracking products, orders, and stock levels.",
    tech_stack: ["Java", "Spring Boot", "MySQL"],
  },
  {
    id: 5,
    project_title: "Weather Forecasting App",
    project_description: "A weather app that provides real-time weather forecasts for user-specified locations.",
    tech_stack: ["Swift", "OpenWeatherMap API"],
  },
  {
    id: 6,
    project_title: "Online Learning Platform",
    project_description: "An e-learning platform for courses and tutorials.",
    tech_stack: ["Ruby on Rails", "PostgreSQL"],
  },
  {
    id: 7,
    project_title: "Chat Application",
    project_description: "A real-time chat application with user-to-user messaging and group chats.",
    tech_stack: ["React", "Node.js", "Socket.io"],
  },
  {
    id: 8,
    project_title: "Travel Booking Website",
    project_description: "A website for booking flights, hotels, and vacation packages.",
    tech_stack: ["HTML/CSS", "JavaScript", "PHP", "MySQL"],
  },
  {
    id: 9,
    project_title: "Task Management Tool",
    project_description: "A tool for managing tasks and to-do lists.",
    tech_stack: ["Angular", "Node.js", "MongoDB"],
  },
  {
    id: 10,
    project_title: "Restaurant Reservation System",
    project_description: "A system for making online reservations at restaurants.",
    tech_stack: ["Java", "Spring Boot", "MySQL"],
  },
  {
    id: 11,
    project_title: "Music Streaming Service",
    project_description: "A music streaming platform with playlists and recommendations.",
    tech_stack: ["React", "Node.js", "MongoDB"],
  },
  {
    id: 12,
    project_title: "Event Ticketing System",
    project_description: "An online platform for buying and selling event tickets.",
    tech_stack: ["PHP", "MySQL"],
  },
  {
    id: 13,
    project_title: "Health and Fitness App",
    project_description: "A mobile app for tracking workouts and diet plans.",
    tech_stack: ["Flutter", "Firebase"],
  },
  {
    id: 14,
    project_title: "Blog Website",
    project_description: "A platform for creating and sharing blogs and articles.",
    tech_stack: ["Python", "Django", "SQLite"],
  },
  {
    id: 15,
    project_title: "Online Marketplace",
    project_description: "An online marketplace for buying and selling various products.",
    tech_stack: ["Ruby on Rails", "PostgreSQL"],
  },
]